/*
 * Java domain class for entity "Address" 
 * Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:01 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.hoa.repositories;
import com.hoa.entities.Address;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * <h2>AddressRepository</h2>
 *
 * createdAt : 2024-04-22 - Time 21:42:01
 * <p>
 * Description: Spring Data repository for the {@link Address} entity.
 * 
 * @author aek
 */
@Repository
public interface AddressRepository  extends JpaRepository<Address, Integer> , JpaSpecificationExecutor<Address> {

}
