/*
 * Java domain class for entity "Amenitytype" 
 * Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.hoa.repositories;
import com.hoa.entities.AmenityType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * <h2>AmenitytypeRepository</h2>
 *
 * createdAt : 2024-04-22 - Time 21:42:02
 * <p>
 * Description: Spring Data repository for the {@link AmenityType} entity.
 * 
 * @author aek
 */
@Repository
public interface AmenitytypeRepository  extends JpaRepository<AmenityType, Integer> , JpaSpecificationExecutor<AmenityType> {

}
