/*
 * Java domain class for entity "Amenitybooking" 
 * Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.hoa.repositories;
import com.hoa.entities.AmenityBooking;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
 * <h2>AmenitybookingRepository</h2>
 *
 * createdAt : 2024-04-22 - Time 21:42:02
 * <p>
 * Description: Spring Data repository for the {@link AmenityBooking} entity.
 * 
 * @author aek
 */
@Repository
public interface AmenitybookingRepository  extends JpaRepository<AmenityBooking, Integer> , JpaSpecificationExecutor<AmenityBooking> {

}
