/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:01 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.Address;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link Address}.
*  @author aek
 */
public interface AddressService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Address
     */
    Address create(Address d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Address
     */
    Address update(Address d);

    /**
     * get Address by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Address
     */
    Address getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Address>
     */
    List<Address> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);

    /**
     * Find all with pagination
     *
     * @return Page<Address>  
     */
    Page<Address> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Address>  
     */
	Page<Address> findAllSpecification(Specification<Address> specs, Pageable pageable);

}
