/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:02 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.Client;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link Client}.
*  @author aek
 */
public interface ClientService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Client
     */
    Client create(Client d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Client
     */
    Client update(Client d);

    /**
     * get Client by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Client
     */
    Client getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Client>
     */
    List<Client> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);

    /**
     * Find all with pagination
     *
     * @return Page<Client>  
     */
    Page<Client> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Client>  
     */
	Page<Client> findAllSpecification(Specification<Client> specs, Pageable pageable);

}
