/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.Faq;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link Faq}.
*  @author aek
 */
public interface FaqService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Faq
     */
    Faq create(Faq d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Faq
     */
    Faq update(Faq d);

    /**
     * get Faq by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Faq
     */
    Faq getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Faq>
     */
    List<Faq> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);

    /**
     * Find all with pagination
     *
     * @return Page<Faq>  
     */
    Page<Faq> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Faq>  
     */
	Page<Faq> findAllSpecification(Specification<Faq> specs, Pageable pageable);

}
