/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.Page;



import java.util.List;

/**
 * Service Interface for managing {@link Page}.
*  @author aek
 */
public interface PageService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Page
     */
    Page create(Page d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Page
     */
    Page update(Page d);

    /**
     * get Page by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Page
     */
    Page getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Page>
     */
    List<Page> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);



}
