/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.Role;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link Role}.
*  @author aek
 */
public interface RoleService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Role
     */
    Role create(Role d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Role
     */
    Role update(Integer roleId,Role role);

    /**
     * get Role by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Role
     */
    Role getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Role>
     */
    List<Role> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);

    /**
     * Find all with pagination
     *
     * @return Page<Role>  
     */
    Page<Role> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Role>  
     */
	Page<Role> findAllSpecification(Specification<Role> specs, Pageable pageable);

}
