/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.RolePage;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link RolePage}.
*  @author aek
 */
public interface RolepageService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity Rolepage
     */
    RolePage create(RolePage d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return Rolepage
     */
    RolePage update(RolePage d);

    /**
     * get Rolepage by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return Rolepage
     */
    RolePage getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<Rolepage>
     */
    List<RolePage> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);

    /**
     * Find all with pagination
     *
     * @return Page<Rolepage>  
     */
    Page<RolePage> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<Rolepage>  
     */
	Page<RolePage> findAllSpecification(Specification<RolePage> specs, Pageable pageable);

}
