/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:04 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.service;
import com.hoa.entities.State;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;

import java.util.List;

/**
 * Service Interface for managing {@link State}.
*  @author aek
 */
public interface StateService  {
   
    /**
     * create new item for domain
     *
     * @param entity entity to save.
     * @return persisted entity State
     */
    State create(State d);

    /**
     * Update entity. Check before if existing data. If data is empty throw Exception
     *
     * @param entity domain
     * @param id of entity
     * @return State
     */
    State update(State d);

    /**
     * get State by id. Can be return empty
     *
     * @param id the id of the entity.
     * @return State
     */
    State getOne(Integer id) ;

    /**
     * Get all entities
     *
     * @return list of entities List<State>
     */
    List<State> getAll();

    /**
     * Count item in entity
     *
     * @return long 
     */
    long getTotal();

    /**
     * Delete record by id
     *  
     */
    void delete(Integer id);

    /**
     * Find all with pagination
     *
     * @return Page<State>  
     */
    Page<State> findAllPaginate(Pageable pageable);

    /**
     * Find all with pagination  by criteria 
     *
     * @return Page<State>  
     */
	Page<State> findAllSpecification(Specification<State> specs, Pageable pageable);

}
