/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:02 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.ClientAddress;
import com.hoa.service.ClientaddressService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link ClientAddress}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/clientaddress")
public class ClientaddressController {

    private final Logger log = LoggerFactory.getLogger(ClientaddressController.class);
	
    private final ClientaddressService entityService;

 	public ClientaddressController (ClientaddressService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /clientaddress} : Create a new clientaddress.
     *
     * @param clientaddress the clientaddress to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new clientaddress.
     */
	@PostMapping("/add")
	public ResponseEntity<ClientAddress> createClientaddress(@RequestBody @Valid ClientAddress clientaddress) {
         log.debug("REST request to save Clientaddress : {}", clientaddress);
         return new ResponseEntity<>(entityService.create(clientaddress), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /clientaddress} : Updates an existing clientaddress.
     *
     * @param clientaddress the clientaddress to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated clientaddress,
     * or with status {@code 400 (Bad Request)} if the clientaddress is not valid,
     * or with status {@code 500 (Internal Server Error)} if the clientaddress couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<ClientAddress> updateClientaddress(@Valid @RequestBody ClientAddress clientaddress) {
        log.debug("REST request to update Clientaddress : {}", clientaddress);
        ClientAddress result = entityService.update(clientaddress);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /clientaddress} : get all the clientaddresss.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of clientaddress in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<ClientAddress>> getAllClientaddress() {
	    log.debug("REST request to get all clientaddresss");
        List<ClientAddress> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /clientaddress/:id} : get the "id" clientaddress.
     *
     * @param id the id of the clientaddress to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the clientaddress, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<ClientAddress> getOneClientaddress(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Clientaddress : {}", id);
        ClientAddress e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /clientaddress/:id} : delete the "id" clientaddress.
     *
     * @param id the id of the clientaddress to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteClientaddress(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Clientaddress : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
