/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:02 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.CommunityDocument;
import com.hoa.service.CommunitydocumentService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link CommunityDocument}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/communitydocument")
public class CommunitydocumentController {

    private final Logger log = LoggerFactory.getLogger(CommunitydocumentController.class);
	
    private final CommunitydocumentService entityService;

 	public CommunitydocumentController (CommunitydocumentService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /communitydocument} : Create a new communitydocument.
     *
     * @param communitydocument the communitydocument to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new communitydocument.
     */
	@PostMapping("/add")
	public ResponseEntity<CommunityDocument> createCommunitydocument(@RequestBody @Valid CommunityDocument communitydocument) {
         log.debug("REST request to save Communitydocument : {}", communitydocument);
         return new ResponseEntity<>(entityService.create(communitydocument), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /communitydocument} : Updates an existing communitydocument.
     *
     * @param communitydocument the communitydocument to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated communitydocument,
     * or with status {@code 400 (Bad Request)} if the communitydocument is not valid,
     * or with status {@code 500 (Internal Server Error)} if the communitydocument couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<CommunityDocument> updateCommunitydocument(@Valid @RequestBody CommunityDocument communitydocument) {
        log.debug("REST request to update Communitydocument : {}", communitydocument);
        CommunityDocument result = entityService.update(communitydocument);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /communitydocument} : get all the communitydocuments.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of communitydocument in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<CommunityDocument>> getAllCommunitydocument() {
	    log.debug("REST request to get all communitydocuments");
        List<CommunityDocument> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /communitydocument/:id} : get the "id" communitydocument.
     *
     * @param id the id of the communitydocument to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the communitydocument, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<CommunityDocument> getOneCommunitydocument(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Communitydocument : {}", id);
        CommunityDocument e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /communitydocument/:id} : delete the "id" communitydocument.
     *
     * @param id the id of the communitydocument to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteCommunitydocument(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Communitydocument : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
