/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:02 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.Designation;
import com.hoa.service.DesignationService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Designation}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/designation")
public class DesignationController {

    private final Logger log = LoggerFactory.getLogger(DesignationController.class);
	
    private final DesignationService entityService;

 	public DesignationController (DesignationService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /designation} : Create a new designation.
     *
     * @param designation the designation to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new designation.
     */
	@PostMapping("/add")
	public ResponseEntity<Designation> createDesignation(@RequestBody @Valid Designation designation) {
         log.debug("REST request to save Designation : {}", designation);
         return new ResponseEntity<>(entityService.create(designation), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /designation} : Updates an existing designation.
     *
     * @param designation the designation to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated designation,
     * or with status {@code 400 (Bad Request)} if the designation is not valid,
     * or with status {@code 500 (Internal Server Error)} if the designation couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<Designation> updateDesignation(@Valid @RequestBody Designation designation) {
        log.debug("REST request to update Designation : {}", designation);
        Designation result = entityService.update(designation);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /designation} : get all the designations.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of designation in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<Designation>> getAllDesignation() {
	    log.debug("REST request to get all designations");
        List<Designation> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /designation/:id} : get the "id" designation.
     *
     * @param id the id of the designation to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the designation, or with status {@code 404 (Not Found)}.
     */
    @GetMapping( "/getOne/{id}")
    public ResponseEntity<Designation> getOneDesignation(@PathVariable(value ="id") Integer id) {
        log.debug("REST request to get Designation : {}", id);
        Designation e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /designation/:id} : delete the "id" designation.
     *
     * @param id the id of the designation to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteDesignation(@PathVariable(value ="id") Integer id) {
        log.debug("REST request to delete Designation : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
