/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.Enquiry;
import com.hoa.service.EnquiryService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Enquiry}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/enquiry")
public class EnquiryController {

    private final Logger log = LoggerFactory.getLogger(EnquiryController.class);
	
    private final EnquiryService entityService;

 	public EnquiryController (EnquiryService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /enquiry} : Create a new enquiry.
     *
     * @param enquiry the enquiry to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new enquiry.
     */
	@PostMapping("/add")
	public ResponseEntity<Enquiry> createEnquiry(@RequestBody @Valid Enquiry enquiry) {
         log.debug("REST request to save Enquiry : {}", enquiry);
         return new ResponseEntity<>(entityService.create(enquiry), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /enquiry} : Updates an existing enquiry.
     *
     * @param enquiry the enquiry to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated enquiry,
     * or with status {@code 400 (Bad Request)} if the enquiry is not valid,
     * or with status {@code 500 (Internal Server Error)} if the enquiry couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<Enquiry> updateEnquiry(@Valid @RequestBody Enquiry enquiry) {
        log.debug("REST request to update Enquiry : {}", enquiry);
        Enquiry result = entityService.update(enquiry);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /enquiry} : get all the enquirys.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of enquiry in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<Enquiry>> getAllEnquiry() {
	    log.debug("REST request to get all enquirys");
        List<Enquiry> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /enquiry/:id} : get the "id" enquiry.
     *
     * @param id the id of the enquiry to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the enquiry, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<Enquiry> getOneEnquiry(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Enquiry : {}", id);
        Enquiry e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /enquiry/:id} : delete the "id" enquiry.
     *
     * @param id the id of the enquiry to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteEnquiry(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Enquiry : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
