/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.Faq;
import com.hoa.service.FaqService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Faq}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/faq")
public class FaqController {

    private final Logger log = LoggerFactory.getLogger(FaqController.class);
	
    private final FaqService entityService;

 	public FaqController (FaqService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /faq} : Create a new faq.
     *
     * @param faq the faq to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new faq.
     */
	@PostMapping("/add")
	public ResponseEntity<Faq> createFaq(@RequestBody @Valid Faq faq) {
         log.debug("REST request to save Faq : {}", faq);
         return new ResponseEntity<>(entityService.create(faq), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /faq} : Updates an existing faq.
     *
     * @param faq the faq to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated faq,
     * or with status {@code 400 (Bad Request)} if the faq is not valid,
     * or with status {@code 500 (Internal Server Error)} if the faq couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<Faq> updateFaq(@Valid @RequestBody Faq faq) {
        log.debug("REST request to update Faq : {}", faq);
        Faq result = entityService.update(faq);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /faq} : get all the faqs.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of faq in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<Faq>> getAllFaq() {
	    log.debug("REST request to get all faqs");
        List<Faq> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /faq/:id} : get the "id" faq.
     *
     * @param id the id of the faq to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the faq, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<Faq> getOneFaq(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Faq : {}", id);
        Faq e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /faq/:id} : delete the "id" faq.
     *
     * @param id the id of the faq to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteFaq(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Faq : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
