/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.HoaFee;
import com.hoa.service.HoafeeService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link HoaFee}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/hoafee")
public class HoafeeController {

    private final Logger log = LoggerFactory.getLogger(HoafeeController.class);
	
    private final HoafeeService entityService;

 	public HoafeeController (HoafeeService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /hoafee} : Create a new hoafee.
     *
     * @param hoafee the hoafee to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new hoafee.
     */
	@PostMapping("/add")
	public ResponseEntity<HoaFee> createHoafee(@RequestBody @Valid HoaFee hoafee) {
         log.debug("REST request to save Hoafee : {}", hoafee);
         return new ResponseEntity<>(entityService.create(hoafee), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /hoafee} : Updates an existing hoafee.
     *
     * @param hoafee the hoafee to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated hoafee,
     * or with status {@code 400 (Bad Request)} if the hoafee is not valid,
     * or with status {@code 500 (Internal Server Error)} if the hoafee couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<HoaFee> updateHoafee(@Valid @RequestBody HoaFee hoafee) {
        log.debug("REST request to update Hoafee : {}", hoafee);
        HoaFee result = entityService.update(hoafee);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /hoafee} : get all the hoafees.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of hoafee in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<HoaFee>> getAllHoafee() {
	    log.debug("REST request to get all hoafees");
        List<HoaFee> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /hoafee/:id} : get the "id" hoafee.
     *
     * @param id the id of the hoafee to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the hoafee, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<HoaFee> getOneHoafee(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Hoafee : {}", id);
        HoaFee e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /hoafee/:id} : delete the "id" hoafee.
     *
     * @param id the id of the hoafee to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteHoafee(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Hoafee : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
