/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.News;
import com.hoa.service.NewsService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link News}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/news")
public class NewsController {

    private final Logger log = LoggerFactory.getLogger(NewsController.class);
	
    private final NewsService entityService;

 	public NewsController (NewsService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /news} : Create a new news.
     *
     * @param news the news to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new news.
     */
	@PostMapping("/add")
	public ResponseEntity<News> createNews(@RequestBody @Valid News news) {
         log.debug("REST request to save News : {}", news);
         return new ResponseEntity<>(entityService.create(news), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /news} : Updates an existing news.
     *
     * @param news the news to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated news,
     * or with status {@code 400 (Bad Request)} if the news is not valid,
     * or with status {@code 500 (Internal Server Error)} if the news couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<News> updateNews(@Valid @RequestBody News news) {
        log.debug("REST request to update News : {}", news);
        News result = entityService.update(news);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /news} : get all the newss.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of news in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<News>> getAllNews() {
	    log.debug("REST request to get all newss");
        List<News> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /news/:id} : get the "id" news.
     *
     * @param id the id of the news to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the news, or with status {@code 404 (Not Found)}.
     */
    @GetMapping( "/getOne/{id}")
    public ResponseEntity<News> getOneNews(@PathVariable(value ="id") Integer id) {
        log.debug("REST request to get News : {}", id);
        News e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /news/:id} : delete the "id" news.
     *
     * @param id the id of the news to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteNews(@PathVariable(value ="id") Integer id) {
        log.debug("REST request to delete News : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
