/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.PlanDetail;
import com.hoa.service.PlandetailService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link PlanDetail}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/plandetail")
public class PlandetailController {

    private final Logger log = LoggerFactory.getLogger(PlandetailController.class);
	
    private final PlandetailService entityService;

 	public PlandetailController (PlandetailService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /plandetail} : Create a new plandetail.
     *
     * @param plandetail the plandetail to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new plandetail.
     */
	@PostMapping("/add")
	public ResponseEntity<PlanDetail> createPlandetail(@RequestBody @Valid PlanDetail plandetail) {
         log.debug("REST request to save Plandetail : {}", plandetail);
         return new ResponseEntity<>(entityService.create(plandetail), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /plandetail} : Updates an existing plandetail.
     *
     * @param plandetail the plandetail to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated plandetail,
     * or with status {@code 400 (Bad Request)} if the plandetail is not valid,
     * or with status {@code 500 (Internal Server Error)} if the plandetail couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<PlanDetail> updatePlandetail(@Valid @RequestBody PlanDetail plandetail) {
        log.debug("REST request to update Plandetail : {}", plandetail);
        PlanDetail result = entityService.update(plandetail);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /plandetail} : get all the plandetails.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of plandetail in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<PlanDetail>> getAllPlandetail() {
	    log.debug("REST request to get all plandetails");
        List<PlanDetail> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /plandetail/:id} : get the "id" plandetail.
     *
     * @param id the id of the plandetail to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the plandetail, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<PlanDetail> getOnePlandetail(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Plandetail : {}", id);
        PlanDetail e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /plandetail/:id} : delete the "id" plandetail.
     *
     * @param id the id of the plandetail to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deletePlandetail(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Plandetail : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
