/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.RolePage;
import com.hoa.service.RolepageService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link RolePage}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/rolepage")
public class RolepageController {

    private final Logger log = LoggerFactory.getLogger(RolepageController.class);
	
    private final RolepageService entityService;

 	public RolepageController (RolepageService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /rolepage} : Create a new rolepage.
     *
     * @param rolepage the rolepage to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new rolepage.
     */
	@PostMapping("/add")
	public ResponseEntity<RolePage> createRolepage(@RequestBody @Valid RolePage rolepage) {
         log.debug("REST request to save Rolepage : {}", rolepage);
         return new ResponseEntity<>(entityService.create(rolepage), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /rolepage} : Updates an existing rolepage.
     *
     * @param rolepage the rolepage to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated rolepage,
     * or with status {@code 400 (Bad Request)} if the rolepage is not valid,
     * or with status {@code 500 (Internal Server Error)} if the rolepage couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<RolePage> updateRolepage(@Valid @RequestBody RolePage rolepage) {
        log.debug("REST request to update Rolepage : {}", rolepage);
        RolePage result = entityService.update(rolepage);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /rolepage} : get all the rolepages.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of rolepage in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<RolePage>> getAllRolepage() {
	    log.debug("REST request to get all rolepages");
        List<RolePage> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /rolepage/:id} : get the "id" rolepage.
     *
     * @param id the id of the rolepage to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the rolepage, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/delete/{id}")
    public ResponseEntity<RolePage> getOneRolepage(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Rolepage : {}", id);
        RolePage e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /rolepage/:id} : delete the "id" rolepage.
     *
     * @param id the id of the rolepage to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRolepage(@PathVariable("id") Integer id) {
        log.debug("REST request to delete Rolepage : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
