/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.ServiceRequest;
import com.hoa.service.ServicerequestService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link ServiceRequest}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/servicerequest")
public class ServicerequestController {

    private final Logger log = LoggerFactory.getLogger(ServicerequestController.class);
	
    private final ServicerequestService entityService;

 	public ServicerequestController (ServicerequestService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /servicerequest} : Create a new servicerequest.
     *
     * @param servicerequest the servicerequest to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new servicerequest.
     */
	@PostMapping("/add")
	public ResponseEntity<ServiceRequest> createServicerequest(@RequestBody @Valid ServiceRequest servicerequest) {
         log.debug("REST request to save Servicerequest : {}", servicerequest);
         return new ResponseEntity<>(entityService.create(servicerequest), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /servicerequest} : Updates an existing servicerequest.
     *
     * @param servicerequest the servicerequest to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated servicerequest,
     * or with status {@code 400 (Bad Request)} if the servicerequest is not valid,
     * or with status {@code 500 (Internal Server Error)} if the servicerequest couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<ServiceRequest> updateServicerequest(@Valid @RequestBody ServiceRequest servicerequest) {
        log.debug("REST request to update Servicerequest : {}", servicerequest);
        ServiceRequest result = entityService.update(servicerequest);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /servicerequest} : get all the servicerequests.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of servicerequest in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<ServiceRequest>> getAllServicerequest() {
	    log.debug("REST request to get all servicerequests");
        List<ServiceRequest> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /servicerequest/:id} : get the "id" servicerequest.
     *
     * @param id the id of the servicerequest to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the servicerequest, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<ServiceRequest> getOneServicerequest(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Servicerequest : {}", id);
        ServiceRequest e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /servicerequest/:id} : delete the "id" servicerequest.
     *
     * @param id the id of the servicerequest to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteServicerequest(@PathVariable("id") Integer id) {
        log.debug("REST request to delete Servicerequest : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
