/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:04 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.Vendor;
import com.hoa.service.VendorService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Vendor}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/vendor")
public class VendorController {

    private final Logger log = LoggerFactory.getLogger(VendorController.class);
	
    private final VendorService entityService;

 	public VendorController (VendorService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /vendor} : Create a new vendor.
     *
     * @param vendor the vendor to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new vendor.
     */
	@PostMapping("/add")
	public ResponseEntity<Vendor> createVendor(@RequestBody @Valid Vendor vendor) {
         log.debug("REST request to save Vendor : {}", vendor);
         return new ResponseEntity<>(entityService.create(vendor), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /vendor} : Updates an existing vendor.
     *
     * @param vendor the vendor to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated vendor,
     * or with status {@code 400 (Bad Request)} if the vendor is not valid,
     * or with status {@code 500 (Internal Server Error)} if the vendor couldn't be updated.
     */
    @PutMapping("update")
    public ResponseEntity<Vendor> updateVendor(@Valid @RequestBody Vendor vendor) {
        log.debug("REST request to update Vendor : {}", vendor);
        Vendor result = entityService.update(vendor);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /vendor} : get all the vendors.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of vendor in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<Vendor>> getAllVendor() {
	    log.debug("REST request to get all vendors");
        List<Vendor> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /vendor/:id} : get the "id" vendor.
     *
     * @param id the id of the vendor to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the vendor, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<Vendor> getOneVendor(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Vendor : {}", id);
        Vendor e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /vendor/:id} : delete the "id" vendor.
     *
     * @param id the id of the vendor to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteVendor(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Vendor : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
