/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:04 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.Violation;
import com.hoa.service.ViolationService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link Violation}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/violation")
public class ViolationController {

    private final Logger log = LoggerFactory.getLogger(ViolationController.class);
	
    private final ViolationService entityService;

 	public ViolationController (ViolationService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /violation} : Create a new violation.
     *
     * @param violation the violation to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new violation.
     */
	@PostMapping("/add")
	public ResponseEntity<Violation> createViolation(@RequestBody @Valid Violation violation) {
         log.debug("REST request to save Violation : {}", violation);
         return new ResponseEntity<>(entityService.create(violation), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /violation} : Updates an existing violation.
     *
     * @param violation the violation to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated violation,
     * or with status {@code 400 (Bad Request)} if the violation is not valid,
     * or with status {@code 500 (Internal Server Error)} if the violation couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<Violation> updateViolation(@Valid @RequestBody Violation violation) {
        log.debug("REST request to update Violation : {}", violation);
        Violation result = entityService.update(violation);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /violation} : get all the violations.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of violation in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<Violation>> getAllViolation() {
	    log.debug("REST request to get all violations");
        List<Violation> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /violation/:id} : get the "id" violation.
     *
     * @param id the id of the violation to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the violation, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<Violation> getOneViolation(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Violation : {}", id);
        Violation e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /violation/:id} : delete the "id" violation.
     *
     * @param id the id of the violation to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteViolation(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Violation : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
