/*
*  Copyright (c) 2019. All right reserved
* Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:04 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.hoa.controller;

import com.hoa.entities.ViolationType;
import com.hoa.service.ViolationtypeService;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.validation.Valid;
import java.util.List;


/**
 * REST controller for managing {@link ViolationType}.
 *
 * @author @aek
 */
@RestController
@RequestMapping("/api/violationtype")
public class ViolationtypeController {

    private final Logger log = LoggerFactory.getLogger(ViolationtypeController.class);
	
    private final ViolationtypeService entityService;

 	public ViolationtypeController (ViolationtypeService entityService) {
		this.entityService = entityService;
	}

    /**
     * {@code POST  /violationtype} : Create a new violationtype.
     *
     * @param violationtype the violationtype to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new violationtype.
     */
	@PostMapping("/add")
	public ResponseEntity<ViolationType> createViolationtype(@RequestBody @Valid ViolationType violationtype) {
         log.debug("REST request to save Violationtype : {}", violationtype);
         return new ResponseEntity<>(entityService.create(violationtype), HttpStatus.CREATED);
    }

   /**
     * {@code PUT  /violationtype} : Updates an existing violationtype.
     *
     * @param violationtype the violationtype to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated violationtype,
     * or with status {@code 400 (Bad Request)} if the violationtype is not valid,
     * or with status {@code 500 (Internal Server Error)} if the violationtype couldn't be updated.
     */
    @PutMapping("/update")
    public ResponseEntity<ViolationType> updateViolationtype(@Valid @RequestBody ViolationType violationtype) {
        log.debug("REST request to update Violationtype : {}", violationtype);
        ViolationType result = entityService.update(violationtype);
        return ResponseEntity.ok().body(result);
    }

    /**
     * {@code GET  /violationtype} : get all the violationtypes.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of violationtype in body.
     */

    @GetMapping("/getAll")
    public ResponseEntity<List<ViolationType>> getAllViolationtype() {
	    log.debug("REST request to get all violationtypes");
        List<ViolationType> lst = entityService.getAll();

        return new ResponseEntity<>(lst,HttpStatus.OK);
    }

    /**
     * {@code GET  /violationtype/:id} : get the "id" violationtype.
     *
     * @param id the id of the violationtype to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the violationtype, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/getOne/{id}")
    public ResponseEntity<ViolationType> getOneViolationtype(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to get Violationtype : {}", id);
        ViolationType e = entityService.getOne(id);

        return new ResponseEntity<>(e, HttpStatus.OK);
    }

  /**
     * {@code DELETE  /violationtype/:id} : delete the "id" violationtype.
     *
     * @param id the id of the violationtype to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Void> deleteViolationtype(@PathVariable(value = "id") Integer id) {
        log.debug("REST request to delete Violationtype : {}", id);
        entityService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
